name: Demo CRM CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set environment flags
      run: |
        echo "DOCKERHUB_ENABLED=$([[ -n '${{ secrets.DOCKERHUB_USERNAME }}' && -n '${{ secrets.DOCKERHUB_TOKEN }}' ]] && echo true || echo false)" >> $GITHUB_ENV
        echo "GHCR_ENABLED=$([[ -n '${{ secrets.GHCR_TOKEN }}' ]] && echo true || echo false)" >> $GITHUB_ENV

    - name: Log in to Docker Hub
      if: ${{ env.DOCKERHUB_ENABLED == 'true' }}
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Log in to GitHub Container Registry
      if: ${{ env.GHCR_ENABLED == 'true' }}
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}

    - name: Pull existing demo-crm image
      run: docker pull pwstaging/demo-crm:latest

    - name: Retag image
      run: |
        TAG=demo-crm:${{ github.run_number }}
        if [ "${{ env.DOCKERHUB_ENABLED }}" == "true" ]; then
          docker tag pwstaging/demo-crm:latest ${{ secrets.DOCKERHUB_USERNAME }}/$TAG
        else
          docker tag pwstaging/demo-crm:latest ghcr.io/${{ github.repository_owner }}/$TAG
        fi

    - name: Push retagged image
      run: |
        TAG=demo-crm:${{ github.run_number }}
        if [ "${{ env.DOCKERHUB_ENABLED }}" == "true" ]; then
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/$TAG
        else
          docker push ghcr.io/${{ github.repository_owner }}/$TAG
        fi

    - name: Set up kind (Kubernetes in Docker)
      uses: helm/kind-action@v1.8.0

    - name: Deploy to kind cluster
      run: |
        kubectl apply -f k8s/deployment.yaml
        if [ "${{ env.DOCKERHUB_ENABLED }}" == "true" ]; then
          kubectl set image deployment/demo-crm demo-crm=${{ secrets.DOCKERHUB_USERNAME }}/demo-crm:${{ github.run_number }}
        else
          kubectl set image deployment/demo-crm demo-crm=ghcr.io/${{ github.repository_owner }}/demo-crm:${{ github.run_number }}
        fi

    - name: Wait for deployment rollout
      run: kubectl rollout status deployment/demo-crm --timeout=120s

    - name: Port-forward and test app
      run: |
        POD=$(kubectl get pods -l app=demo-crm -o jsonpath='{.items[0].metadata.name}')
        kubectl port-forward $POD 3000:3000 &
        PF_PID=$!
        sleep 15
        echo "Checking if the app responds on http://localhost:3000"
        curl --retry 5 --retry-delay 5 --fail http://localhost:3000 || (echo "App failed to respond" && kill $PF_PID && exit 1)
        kill $PF_PID

    - name: Clean up kind cluster
      if: always()
      run: kind delete cluster
